### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by thelsing** [selfbus/hardware-incubation#11]
Hallo Leute,

wie kann man aktuell mit der mit oldcoolguy & co in Kontakt kommen? Das Forum ist tot. Auf Freenode ist keiner, und für Slack braucht man eine Einladung.

VG
Thomas

**Comment by Doumanix** [comment]
Hi, hier auf Github steht ganz oben: http://www.selfbus.org 
Dort findet man direkt die Links zum neuen Forum https://selbus.org/forum 
Vom Forum geht's auch wieder per Link zu Slack, zum Wiki, zu Github. Außerdem findet man dort einen Thread zu Slack mit einer Einladung: https://selfbus.org/forum/viewtopic.php?f=14&t=576

**Comment by thelsing** [comment]
Ok. Den hab ich nicht gesehen. Danke. Bei den Quicklinks oben rechts auf selfbus.org steht noch der Link zu http://selfbus.forums3.com der aber nicht geht. Vermutlich bin ich nicht der Einzige der dann denkt: Forum ist kaputt. Besonders wenn man eine Weile nicht auf der Seite war.

**Comment by Doumanix** [comment]
Danke für den Hinweis,  das habe ich ganz offensichtlich übersehen. Werde ich sofort eintragen, wenn das Wiki sein Update hinter sich hat und wieder geht.
